
//properties
export const cards=[
{   id:'123',
    img:'https://framerusercontent.com/images/LPsvVxwLIBMzzyZAFCgBAmu8Q.webp?scale-down-to=512',
    title:'Maple Geove',
    location:'4321 Cedar Lane, NY',
    price:'$250,000',
    bedrooms:3,
    bathrooms:1,
    floorPlan: '1',
    buildYear:'2009',
    parkingLots: '1',
    length:'2,100',
    isSale:true ,
    description:'Maple Grove Estate is an exquisite property that combines rustic charm with modern elegance. With sprawling grounds and top-notch facilities, this estate is perfect for those seeking a peaceful retreat in the heart of the city.'    
},
{   id:'456',
    img:'https://framerusercontent.com/images/BeFApd0BHsxGKeT3w5xAG9ehdOk.jpg',
    title:'Pinecresh Villa',
    location:'2321 Villa Land, CA',
    price:'$250,000',
    bedrooms:2,
    bathrooms:1,
    floorPlan: '2',
    buildYear: '2012',
    parkingLots: '1',
    length:'3,100',
    isSale:false,
    description:'Pinecrest Villa stands as a testament to luxury living, offering breathtaking views and state-of-the-art amenities. This villa is designed for those who appreciate fine living and exquisite attention to detail.'
},
{   id:'789',
    img:'https://framerusercontent.com/images/S5hH7eva4Nm6zavJIPlbPtQnNo.jpg',
    title:'Cedar Height',
    location:'4321 Cedar Lane, NY',
    price:'$250,000',
    bedrooms:4,
    bathrooms:1,
    floorPlan: '3',
    buildYear: '2021',
    parkingLots: '2',
    length:'1,100',
    isSale:true ,
     description:'Cedar Heights Apartment is a modern urban sanctuary, featuring sleek design and premium finishes. Located in a vibrant community, this apartment offers an ideal lifestyle for young professionals and families alike.'  
},
{   id:'876',
    img:'https://framerusercontent.com/images/FyefkGsDB4MFaKNg0Z4PCvgjA.jpg',
    title:'Birchwood Townhouse',
    location:'4321 Birchwood  Street, CA',
    price:'$250,000',
    bedrooms:5,
    bathrooms:3,
    floorPlan: '3',
    buildYear: '2020',
    parkingLots: '3',
    length:'3,800',
    isSale:false ,
    description:'Birchwood Townhouse offers contemporary living with a touch of classic elegance. With spacious rooms and modern conveniences, this townhouse is perfect for those who value comfort and style.'
},
{   id:'910',
    img:'https://framerusercontent.com/images/2my6Ls6ma3KSWnsfHEWdGxco.jpg',
    title:'Sunset Ridge Retreat',
    location:'7849 Serenity, CA',
    price:'$250,000',
    bedrooms:8,
    bathrooms:3,
    floorPlan: '6',
    buildYear: '2018',
    parkingLots: '2',
    length:'5,100',
    isSale:true ,
    description:'Sunset Ridge Retreat offers unparalleled views and tranquility, nestled amidst lush greenery. This retreat is designed for those seeking serenity and luxury in a picturesque setting.'
   
},
{   id:'223',
    img:'https://framerusercontent.com/images/LPsvVxwLIBMzzyZAFCgBAmu8Q.webp?scale-down-to=512',
    title:'Serenity Height',
    location:'4321 Avenue, NY',
    price:'$250,000',
    bedrooms:4,
    bathrooms:3,
    floorPlan: '3',
    buildYear: '2013',
    parkingLots: '2',
    length:'3,100',
    isSale:true,
    description:'Serenity Heights Apartment is a modern urban sanctuary, featuring sleek design and premium finishes. Located in a vibrant community, this apartment offers an ideal lifestyle for young professionals and families alike.'   
},
]

//agents
export const agentsData = [
    
    {
    
        url:  "https://framerusercontent.com/images/bDbAKXnf93kg4xgDr2naOX9Hos.jpg",
        name: 'Ethan Carter',
        role:'Senior Consultant',
        phone: '(123) 456-7890',
        email: 'test@example.com',
        location: 'Los Angeles, CA',
        about:'Ethan Carter is a seasoned real estate consultant with a strong track record in helping clients find their dream homes and investment properties. Known for his exceptional negotiation skills and in-depth market knowledge, he prides himself on delivering personalized solutions. ',
        experience: 'With over 9 years of experience in the luxury real estate market, Ethan has successfully brokered multi-million dollar deals in exclusive neighborhoods.She has an eye for luxury details and provides expert advice on the best investment opportunities in the high-end sector. Sophia’s professionalism and commitment to excellence set her apart.',
    },
    {
    
    url:'https://framerusercontent.com/images/I3gfAQe3MC9t15Ya3mItXqXoQ.jpg',
    name: 'Sophia Turner',
        role:'Luxury Specualist',
        phone: '(123) 456-7890',
        email: 'test@example.com',
        location: 'Los Angeles, CA',
        about:'Sophia Turner is a seasoned real estate consultant with a strong track record in helping clients find their dream homes and investment properties. Known for his exceptional negotiation skills and in-depth market knowledge, he prides himself on delivering personalized solutions. ',
        experience: 'With over 11 years of experience in the luxury real estate market, Sophia has successfully brokered multi-million dollar deals in exclusive neighborhoods.She has an eye for luxury details and provides expert advice on the best investment opportunities in the high-end sector. Sophia’s professionalism and commitment to excellence set her apart.',
    },
    {
    
    url: 'https://framerusercontent.com/images/tU4X9bugMWK1LfGleFrokhGKi8.jpg',
    name: 'Naymur Rahman',
        role:'Property Manager',
        phone: '(123) 456-7890',
        email: 'test@example.com',
        location: 'Los Angeles, CA',
        about:'Naymur Rahman is a seasoned real estate consultant with a strong track record in helping clients find their dream homes and investment properties. Known for his exceptional negotiation skills and in-depth market knowledge, he prides himself on delivering personalized solutions. ',
        experience: 'With over 7 years of experience in the luxury real estate market, Naymur has successfully brokered multi-million dollar deals in exclusive neighborhoods.She has an eye for luxury details and provides expert advice on the best investment opportunities in the high-end sector. Sophia’s professionalism and commitment to excellence set her apart.',
    },
    {
    
    url: 'https://framerusercontent.com/images/Kv3esn4UiahiRhRtlUWqTXUu0.jpg',
    name: 'Ava Hamilton',
        role:'Property Consultant',
        phone: '(123) 456-7890',
        email: 'test@example.com',
        location: 'Los Angeles, CA',
        about:'Ava Hamilton is a seasoned real estate consultant with a strong track record in helping clients find their dream homes and investment properties. Known for his exceptional negotiation skills and in-depth market knowledge, he prides himself on delivering personalized solutions. ',
        experience: 'With over 10 years of experience in the luxury real estate market, Ava  has successfully brokered multi-million dollar deals in exclusive neighborhoods.She has an eye for luxury details and provides expert advice on the best investment opportunities in the high-end sector. Sophia’s professionalism and commitment to excellence set her apart.',
    },
    {
    
        url: 'https://framerusercontent.com/images/ROxXw7mHMl35ZpOmxuK3aG14rtc.jpg',
        name: 'Oliver Brooks',
        role:'Leading Specialist',
        phone: '(123) 456-7890',
        email: 'test@example.com',
        location: 'Los Angeles, CA',
        about:'Oliver Brooks is a seasoned real estate consultant with a strong track record in helping clients find their dream homes and investment properties. Known for his exceptional negotiation skills and in-depth market knowledge, he prides himself on delivering personalized solutions. ',
        experience: 'With over 6 years of experience in the luxury real estate market,Oliver has successfully brokered multi-million dollar deals in exclusive neighborhoods.She has an eye for luxury details and provides expert advice on the best investment opportunities in the high-end sector. Sophia’s professionalism and commitment to excellence set her apart.',
    },
    {
    
    url: 'https://framerusercontent.com/images/yuMT38uSZAf5RhP6xfohbl4kpg.jpg',
    name: 'Liam Mitchell',
        role:'Investment Advisor',
        phone: '(123) 456-7890',
        email: 'test@example.com',
        location: 'Los Angeles, CA',
        about:'Liam Mitchell is a seasoned real estate consultant with a strong track record in helping clients find their dream homes and investment properties. Known for his exceptional negotiation skills and in-depth market knowledge, he prides himself on delivering personalized solutions. ',
        experience: 'With over 9 years of experience in the luxury real estate market, Liam has successfully brokered multi-million dollar deals in exclusive neighborhoods.She has an eye for luxury details and provides expert advice on the best investment opportunities in the high-end sector. Sophia’s professionalism and commitment to excellence set her apart.',
    },
   

]